import express from 'express';
import { getDashboardStats, getAchievementStats, getEventStats, getPendingAchievements } from '../controllers/adminController.jsx';
import { verifyAchievement } from '../controllers/achievementController.jsx';
import { updateStudent } from '../controllers/studentController.jsx';
import { protect, authorize } from '../middleware/auth.jsx';
const router = express.Router();
router.use(protect);
router.use(authorize('admin'));
router.get('/dashboard/stats', getDashboardStats);
router.get('/achievements/pending', getPendingAchievements);
router.put('/achievements/:id/verify', verifyAchievement);
router.put('/students/:id', updateStudent);
router.get('/reports/achievements', getAchievementStats);
router.get('/reports/events', getEventStats);
export default router;
